version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "curl -s ifconfig.co"
      #KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-faas-connector:
    build: .
    container_name: kafka-faas-connector
    depends_on:
      - kafka
    environment:
      kafka.bootstrapServers: kafka:9092
      openfaas.gateway: http://host.docker.internal:8080
